version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/config/etc/nginx:/etc/nginx
      - ${PWD}/config/certs:/etc/ssl/private
