version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
      - ./nginx/certs>:/etc/ssl/private
